name: mcat_example
description: "A mcat tool app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mcat_package:
    path: ../mcat_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/face_1.png
    - assets/images/face_2.png
    - assets/images/logo.png
    - assets/images/carp_logo.png