// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUqM6vmxlgWU_oaQGQV7zheivzfNt3GA',
    appId: '1:63672245201:web:a06f31a005130c8e015ef0',
    messagingSenderId: '63672245201',
    projectId: 'mcat-dtu-lummim',
    authDomain: 'mcat-dtu-lummim.firebaseapp.com',
    storageBucket: 'mcat-dtu-lummim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciG_Z7v5J32RRegrJl9FwgMCzgJ8AJ4E',
    appId: '1:63672245201:android:fb187eaa31cb0130015ef0',
    messagingSenderId: '63672245201',
    projectId: 'mcat-dtu-lummim',
    storageBucket: 'mcat-dtu-lummim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDored3SCW8zte8IFoQCeZYevyb3qEOQig',
    appId: '1:63672245201:ios:a2b1a89fd707702c015ef0',
    messagingSenderId: '63672245201',
    projectId: 'mcat-dtu-lummim',
    storageBucket: 'mcat-dtu-lummim.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDored3SCW8zte8IFoQCeZYevyb3qEOQig',
    appId: '1:63672245201:ios:a2b1a89fd707702c015ef0',
    messagingSenderId: '63672245201',
    projectId: 'mcat-dtu-lummim',
    storageBucket: 'mcat-dtu-lummim.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVUqM6vmxlgWU_oaQGQV7zheivzfNt3GA',
    appId: '1:63672245201:web:b75b5ed9d4509ce8015ef0',
    messagingSenderId: '63672245201',
    projectId: 'mcat-dtu-lummim',
    authDomain: 'mcat-dtu-lummim.firebaseapp.com',
    storageBucket: 'mcat-dtu-lummim.firebasestorage.app',
  );
}
